dataset_name: 'soyageingr6'
dataset_root_path: '../../data/soyageing'
df_train: 'train_R6.csv'
df_trainval: train_val_R6.csv
df_val: 'val_R6.csv'
df_test: 'test_R6.csv'
folder_train: '.'
folder_val: '.'
folder_test: '.'
df_classid_classname: False
