dataset_name: 'soyageingr3'
dataset_root_path: '../../data/soyageing'
df_train: 'train_R3.csv'
df_trainval: train_val_R3.csv
df_val: 'val_R3.csv'
df_test: 'test_R3.csv'
folder_train: '.'
folder_val: '.'
folder_test: '.'
df_classid_classname: False
