dataset_name: 'soyageingr4'
dataset_root_path: '../../data/soyageing'
df_train: 'train_R4.csv'
df_trainval: train_val_R4.csv
df_val: 'val_R4.csv'
df_test: 'test_R4.csv'
folder_train: '.'
folder_val: '.'
folder_test: '.'
df_classid_classname: False
